name: Build Gatsby, create share images and deploy to server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm ci
          npm run build
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          local-dir: ./public/
          server-dir: /web/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: true
